---
apiVersion: v1
kind: Template
name: uhc-acct-mangr-routes
metadata:
  name: route

objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: maestro
    labels:
      app: maestro
  spec:
    host: maestro.apps-crc.testing
    to:
      kind: Service
      name: maestro
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
